export const LlmsList = [
  {
    modelName: "Gemini 2.0 Flash",
    modelId: "gemini-2.0-flash-exp",
    shortName: "Gemini 2.0 Flash",
    modelIcon: "/assets/icons/model-icons/gemini.svg",
    provider: "google",
  },
  {
    modelName: "Gemini 1.5 Pro",
    modelId: "gemini-1.5-pro",
    shortName: "Gemini 1.5 Pro",
    modelIcon: "/assets/icons/model-icons/gemini.svg",
    provider: "google",
  },
  {
    modelName: "Gemini 1.5 Flash",
    modelId: "gemini-1.5-flash",
    shortName: "Gemini 1.5 Flash",
    modelIcon: "/assets/icons/model-icons/gemini.svg",
    provider: "google",
  },
];

export const LanguagesList = [
  { code: "ar", name: "Arabic" },
  { code: "as", name: "Assamese" },
  { code: "bn", name: "Bengali" },
  { code: "ceb", name: "Cebuano" },
  { code: "zh", name: "Chinese" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "nl", name: "Dutch" },
  { code: "en", name: "English" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "el", name: "Greek" },
  { code: "gu", name: "Gujarati" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "ne", name: "Nepali" },
  { code: "no", name: "Norwegian" },
  { code: "or", name: "Odia" },
  { code: "fa", name: "Persian" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "sa", name: "Sanskrit" },
  { code: "es", name: "Spanish" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "vi", name: "Vietnamese" },
];

export const GLOBAL_AGENT_META_DATA = {
  agentName: "Global Chat",
  agnoId: "Global_chat",
  description:
    "Try Kroolo's global chat to ask any specific question or search for anything.",
  agentAvatar: "/assets/icons/ChatWithProjectAI.svg",
  referenceName: "Global Chat",
};
